[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
entity = { path = "../entity" }
sea-orm = { version = "0.11", features = [
    "debug-print",
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
serde = { version = "1", features = ["derive"] }
