[package]
authors = ["刘贺贺 <15252114322@163.com>"]
edition = "2021"
name = "api"
publish = false
version = "0.1.0"

[lib]
name = "api"
path = "src/lib.rs"

[dependencies]
actix-web = "4"
entity = { path = "../entity" }
serde = "1"
core = { path = "../core" }
