[server]
address = "0.0.0.0:9765"

[log]
dir = "log" 
enable_oper_log = true 
file = "app_log" 
log_level = "DEBUG" #  TRACE DEBUG  INFO  WARN ERROR

[database]
link = "postgres://postgres:123456@182.160.14.59:30432/zktony"
