[package]
default-run = "zktony-api"
edition = "2021"
name = "zktony-api"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = {path = "../api"}
common = {path = "../common"}
configs = {path = "../configs"}
service = {path = "../service"}
utils = {path = "../utils"}

# axum
axum = {workspace = true, default-features = false}
axum-server = {workspace = true, default-features = false, features = ["tls-rustls"]}
hyper = {workspace = true, default-features = false}
tokio = {workspace = true, default-features = false, features = ["rt-multi-thread", "macros", "parking_lot", "signal"]}
tower-http = {workspace = true, default-features = false, features = ["cors", "fs", "compression-gzip"]}

#
tracing = {workspace = true, default-features = false}
tracing-appender = {workspace = true, default-features = false}
tracing-subscriber = {workspace = true, default-features = false, features = ["json", "env-filter", "local-time", "registry"]}
