[package]
name = "config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toml = "0.7"
once_cell = "1"
serde = { version = "1", features = ["derive"] }

[lib]
path = "./src/lib.rs"
