//
// Created by 刘贺贺 on 2022/9/19.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_com_zktony_socketcan_SocketCAN */

#ifndef _Included_com_zktony_SocketCAN
#define _Included_com_zktony_SocketCAN
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_com_zktony_socketcan_SocketCAN_open(JNIEnv *env, jobject thiz, jstring channel);

JNIEXPORT jint JNICALL
Java_com_zktony_socketcan_SocketCAN_close(JNIEnv *env, jobject thiz, jint fd);

JNIEXPORT jint JNICALL
Java_com_zktony_socketcan_SocketCAN_write(JNIEnv *env, jobject thiz, jint fd, jlong id, jlong eff,
                                          jlong rtr,
                                          jint len, jintArray data);
JNIEXPORT jlongArray JNICALL
Java_com_zktony_socketcan_SocketCAN_read(JNIEnv *env, jobject thiz, jint fd);

#ifdef __cplusplus
}
#endif
#endif