[server]
name = "ZkTony-Api"
version = "0.1.0"
# 服务器ip 端口
address = "0.0.0.0:9765"
# 是否开启 metrics
metrics = false
# 服务器ssl
ssl = false
# 响应数据压缩
content_gzip = true

[metrics]
address = "0.0.0.0:9000"
timeout = 3600

[cert]
cert = "config/cert/cert.pem"
key = "config/cert/key.pem"

[log]
dir = "log" 
enable_oper_log = true 
file = "app_log" 
log_level = "DEBUG" #  TRACE DEBUG  INFO  WARN ERROR

[database]
link = "postgres://postgres:123456@182.160.14.59:30432/zktony"
