package com.zktony.android.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF0059C6)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFD8E2FF)
val light_onPrimaryContainer = Color(0xFF001A43)
val light_secondary = Color(0xFF355CA8)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD9E2FF)
val light_onSecondaryContainer = Color(0xFF001943)
val light_tertiary = Color(0xFF5E4BC1)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE5DEFF)
val light_onTertiaryContainer = Color(0xFF1A0063)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFEFBFF)
val light_onBackground = Color(0xFF1B1B1F)
val light_surface = Color(0xFFFEFBFF)
val light_onSurface = Color(0xFF1B1B1F)
val light_surfaceVariant = Color(0xFFE1E2EC)
val light_onSurfaceVariant = Color(0xFF44474F)
val light_outline = Color(0xFF757780)
val light_inverseOnSurface = Color(0xFFF2F0F4)
val light_inverseSurface = Color(0xFF303034)
val light_inversePrimary = Color(0xFFAFC6FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF0059C6)
val light_outlineVariant = Color(0xFFC5C6D0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFAFC6FF)
val dark_onPrimary = Color(0xFF002D6C)
val dark_primaryContainer = Color(0xFF004397)
val dark_onPrimaryContainer = Color(0xFFD8E2FF)
val dark_secondary = Color(0xFFAFC6FF)
val dark_onSecondary = Color(0xFF002D6C)
val dark_secondaryContainer = Color(0xFF16448F)
val dark_onSecondaryContainer = Color(0xFFD9E2FF)
val dark_tertiary = Color(0xFFC9BFFF)
val dark_onTertiary = Color(0xFF2F0F91)
val dark_tertiaryContainer = Color(0xFF4630A8)
val dark_onTertiaryContainer = Color(0xFFE5DEFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE3E2E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE3E2E6)
val dark_surfaceVariant = Color(0xFF44474F)
val dark_onSurfaceVariant = Color(0xFFC5C6D0)
val dark_outline = Color(0xFF8E9099)
val dark_inverseOnSurface = Color(0xFF1B1B1F)
val dark_inverseSurface = Color(0xFFE3E2E6)
val dark_inversePrimary = Color(0xFF0059C6)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFAFC6FF)
val dark_outlineVariant = Color(0xFF44474F)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1678FF)