//
// Created by 刘贺贺 on 2022/9/19.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_com_zktony_serialport_core_SerialPort */

#ifndef _Included_com_zktony_SerialPort
#define _Included_com_zktony_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_com_zktony_serialport_core_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_zktony_serialport_core_SerialPort_open
        (JNIEnv *, jobject thiz, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Java_com_zktony_serialport_core_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zktony_serialport_core_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif