[package]
edition = "2021"
name = "zktony_core"
version = "0.1.0"

[dependencies]
chrono = "0.4.23"
entity = {path = "../entity"}
sea-orm = {version = "0.11.0", features = ["sqlx-postgres", "runtime-actix-native-tls", "macros"]}
serde = {version = "1.0", features = ["derive"]}
