[package]
name = "zktony_core"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }
chrono = "0.4.23"
serde = { version = "1.0", features = ["derive"] }
sea-orm = { version = "0.11.0", features = ["sqlx-postgres", "runtime-actix-native-tls", "macros"] }
