name: ZkTony-WEB

on:
  push:
    branches:
      - main
    paths:
      - 'ZkTony-WEB/**'
  pull_request:
    paths:
      - 'ZkTony-WEB/**'

env:
  SAMPLE_PATH: ZkTony-WEB

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties        

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Generate cache key
        run: ./scripts/checksum.sh $SAMPLE_PATH checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Change wrapper permissions
        working-directory: ${{ env.SAMPLE_PATH }}
        run: chmod +x ./gradlew

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew bootBuildImage
