[package]
edition = "2021"
name = "entity"
publish = false
version = "0.1.0"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
